#!/bin/bash
apt-get update -y
apt-get install git -y
git clone https://github.com/goodtft/LCD-show.git
cd LCD-show
cp ./usr/tft35a-overlay.dtb /boot/overlays/tft35a.dtbo
cp ./usr/cmdline.txt /boot
echo dtoverlay=tft35a >> /boot/config.txt 
reboot
